services:
  renterd:
    image: ghcr.io/siafoundation/renterd
    restart: always
    container_name: renterd
    volumes:
      - ./renterd/:/data
    ports:
      - 9980:9980
      - 8080:8080

  jellyfin:
    image: skunkink/renterd-jellyfin
    restart: always
    container_name: jellyfin
    environment:
      S3_BUCKET: ${S3_BUCKET:-default}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL:-http://renterd:8080}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
    ports:
      - 8096:8096
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    depends_on:
      renterd:
        condition: service_started